export const rolesData = [
  { id: "loup-garou", name: "Loup-Garou", description: "Chaque nuit, vous vous réveillez avec les autres Loups-Garous pour dévorer un villageois. Le jour, vous essayez de cacher votre identité.", color: "#dc2626", image: "" },
  { id: "voyante", name: "Voyante", description: "Chaque nuit, vous pouvez découvrir la véritable identité d'un joueur de votre choix.", color: "#9333ea", image: "" },
  { id: "sorciere", name: "Sorcière", description: "Vous possédez deux potions : une de guérison pour ressusciter le joueur tué par les loups, et une d'empoisonnement pour éliminer un joueur.", color: "#16a34a", image: "" },
  { id: "chasseur", name: "Chasseur", description: "Si vous êtes tué, vous avez le pouvoir de répliquer avant de mourir en éliminant un autre joueur.", color: "#ea580c", image: "" },
  { id: "villageois", name: "Simple Villageois", description: "Vous n'avez aucun pouvoir particulier. Votre seule arme est votre force de persuasion pour éliminer les Loups-Garous.", color: "#d97706", image: "" },
  { id: "cupidon", name: "Cupidon", description: "La première nuit, vous désignez deux joueurs qui seront follement amoureux. Si l'un meurt, l'autre meurt de chagrin immédiatement.", color: "#ec4899", image: "" },
  { id: "petite-fille", name: "Petite Fille", description: "Pendant que les Loups-Garous se réveillent, vous pouvez entrouvrir les yeux pour essayer de les démasquer.", color: "#2563eb", image: "" },
  { id: "voleur", name: "Voleur", description: "La première nuit, vous pourrez échanger votre rôle contre l'une des deux cartes non distribuées, si vous le souhaitez.", color: "#52525b", image: "" },
  { id: "joueur-flute", name: "Joueur de Flûte", description: "Chaque nuit, vous charmez deux nouveaux joueurs. Vous gagnez la partie si tous les joueurs vivants sont charmés.", color: "#14b8a6", image: "" },
  { id: "idiot-village", name: "L'Idiot du Village", description: "Si le village vote contre vous, vous êtes gracié mais perdez votre droit de vote pour le reste de la partie.", color: "#84cc16", image: "" },
  { id: "ancien", name: "L'Ancien", description: "Vous survivez à la première attaque des Loups-Garous. Si vous êtes tué par le village, la Sorcière ou le Chasseur, tous les villageois perdent leurs pouvoirs.", color: "#64748b", image: "" },
  { id: "bouc-emissaire", name: "Bouc Émissaire", description: "En cas d'égalité lors du vote du village, c'est toujours vous qui mourez. Vous désignez alors qui pourra voter le lendemain.", color: "#f59e0b", image: "" },
  { id: "salvateur", name: "Le Salvateur", description: "Chaque nuit, vous protégez un joueur de l'attaque des Loups-Garous. Vous ne pouvez pas protéger la même personne deux nuits de suite.", color: "#0ea5e9", image: "" },
  { id: "loup-blanc", name: "Loup-Garou Blanc", description: "Vous gagnez seul. Une nuit sur deux, vous pouvez dévorer un autre Loup-Garou en plus de la victime normale.", color: "#e2e8f0", image: "" },
  { id: "corbeau", name: "Le Corbeau", description: "Chaque nuit, vous désignez un joueur suspect. Ce joueur aura d'office deux voix contre lui lors du vote du lendemain.", color: "#334155", image: "" },
  { id: "ange", name: "L'Ange", description: "Si vous parvenez à vous faire éliminer lors du tout premier vote du village, vous gagnez la partie seul immédiatement.", color: "#f8fafc", image: "" },
  { id: "grand-mechant-loup", name: "Grand Méchant Loup", description: "Tant qu'aucun Loup-Garou n'est mort, vous pouvez dévorer un villageois supplémentaire chaque nuit.", color: "#7f1d1d", image: "" },
  { id: "enfant-sauvage", name: "L'Enfant Sauvage", description: "La première nuit, vous choisissez un modèle. Si ce modèle meurt, vous devenez un Loup-Garou.", color: "#b45309", image: "" },
  { id: "chien-loup", name: "Le Chien-Loup", description: "La première nuit, vous décidez si vous voulez être un simple villageois ou rejoindre le camp des Loups-Garous.", color: "#a1a1aa", image: "" },
  { id: "renard", name: "Le Renard", description: "La nuit, vous désignez 3 joueurs voisins. S'il y a un Loup-Garou parmi eux, vous conservez votre pouvoir pour la nuit suivante, sinon vous le perdez.", color: "#f97316", image: "" },
  { id: "soeurs", name: "Deux Sœurs", description: "La première nuit, vous vous réveillez pour vous reconnaître. Vous savez que vous êtes toutes les deux d'innocentes villageoises.", color: "#f472b6", image: "" },
  { id: "freres", name: "Trois Frères", description: "La première nuit, vous vous réveillez pour vous reconnaître. Vous formez une alliance solide de villageois.", color: "#3b82f6", image: "" },
  { id: "juge-begue", name: "Le Juge Bègue", description: "Une fois dans la partie, vous pouvez provoquer un deuxième vote consécutif du village le même jour.", color: "#8b5cf6", image: "" },
  { id: "chevalier-epee", name: "Chevalier à l'Épée Rouillée", description: "Si vous êtes dévoré par les Loups-Garous, le premier Loup qui vous a attaqué mourra la nuit suivante.", color: "#9ca3af", image: "" },
  { id: "comedien", name: "Le Comédien", description: "La première nuit, le MJ choisit 3 cartes de rôles à pouvoirs. Chaque nuit, vous pouvez choisir d'utiliser l'un de ces pouvoirs (une fois chacun).", color: "#fbbf24", image: "" },
  { id: "montreur-ours", name: "Montreur d'Ours", description: "Chaque matin, si un Loup-Garou se trouve immédiatement à côté de vous, le MJ fait grogner l'ours.", color: "#78350f", image: "" },
  { id: "pyromane", name: "Le Pyromane", description: "Chaque nuit, vous pouvez brûler une maison ou n'en faire rien. Si la maison appartient à la victime des loups, elle est sauvée. Sinon, le propriétaire meurt.", color: "#ef4444", image: "" },
  { id: "ankou", name: "L'Ankou", description: "Vous êtes le fossoyeur. La nuit, vous savez qui va mourir, et pouvez voter secrètement le lendemain même si vous êtes éliminé.", color: "#1e293b", image: "" },
  { id: "infect-pere-des-loups", name: "Infect Père des Loups", description: "Une fois dans la partie, après que les loups ont fait leur victime, vous pouvez l'infecter au lieu de la tuer : elle devient un Loup-Garou.", color: "#450a0a", image: "" },
  { id: "renard-garou", name: "Renard-Garou", description: "Mi-renard, mi-loup. Vous gagnez avec les loups, mais vous pouvez détecter les rôles à la manière du renard.", color: "#c2410c", image: "" },
  { id: "garde-champetre", name: "Garde Champêtre", description: "Vous êtes nommé par le maire. Vous pouvez distribuer des blâmes ou des décorations influençant le vote.", color: "#059669", image: "" },
  { id: "sectaire", name: "Le Sectaire", description: "La première nuit, le MJ divise le village en deux. Vous devez éliminer tous les membres de la secte adverse pour gagner.", color: "#be185d", image: "" },
  { id: "louveteau", name: "Le Louveteau", description: "Si vous êtes tué, les Loups-Garous font deux victimes la nuit suivante pour vous venger.", color: "#991b1b", image: "" },
  { id: "chasseur-tetes", name: "Chasseur de Têtes", description: "Vous gagnez seul si le joueur qui vous a été désigné comme cible est éliminé par le vote du village.", color: "#b91c1c", image: "" },
  { id: "barbier", name: "Le Barbier", description: "Pendant la journée, vous pouvez éliminer le joueur de votre choix au risque de votre propre vie si c'est un innocent.", color: "#6b7280", image: "" },
  { id: "confesseur", name: "Le Confesseur", description: "Une fois dans la partie, vous pouvez obliger un joueur à vous révéler sa carte en privé.", color: "#4f46e5", image: "" },
  { id: "alchimiste", name: "L'Alchimiste", description: "Vous distribuez secrètement des potions aux joueurs. L'une tue, l'autre rend invincible pour une nuit.", color: "#0d9488", image: "" },
  { id: "devin", name: "Le Devin", description: "La première nuit, vous pouvez découvrir combien de joueurs possèdent des pouvoirs spéciaux.", color: "#a855f7", image: "" },
  { id: "charmeuse", name: "La Charmeuse", description: "Si vous survivez jusqu'aux 3 derniers joueurs, vous gagnez obligatoirement la partie peu importe votre camp initial.", color: "#f43f5e", image: "" },
  { id: "illusionniste", name: "L'Illusionniste", description: "Une fois par partie, vous pouvez échanger virtuellement les places de deux joueurs lors du vote.", color: "#d946ef", image: "" }
];
